# Generated by Django 4.0 on 2023-11-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_faq_answer_lc_faq_question_lc'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='offer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
