# Generated by Django 4.0 on 2023-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_inventory_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='lang',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
