# Generated by Django 4.0 on 2023-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_businessunit_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceholiday',
            name='day_nm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='serviceholiday',
            name='off',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
