# Generated by Django 4.0 on 2023-11-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_appcategory_alter_appointment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Description_cl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_cl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
