# Generated by Django 4.0 on 2023-11-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_appointment_description_cl_appointment_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceholiday',
            name='day_cl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
