# Generated by Django 4.0 on 2023-11-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_slotbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcategory',
            name='mcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.businesscategory'),
        ),
        migrations.AddField(
            model_name='invcategory',
            name='mcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.businesscategory'),
        ),
    ]
