# Generated by Django 4.0 on 2023-11-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_appcategory_mcat_invcategory_mcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='plan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
