# Generated by Django 4.0 on 2023-11-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_clincsub_clincdays_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clincdays',
            name='section',
        ),
    ]
