# Generated by Django 4.0 on 2023-11-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_remove_clincdays_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='h_url',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
