# Generated by Django 4.0 on 2023-11-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_inventory_h_url_inventory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceholiday',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceholiday',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
