# Generated by Django 4.0 on 2023-11-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_serviceholiday_end_serviceholiday_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='ph_acc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='ph_tkn',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
