# Generated by Django 4.0 on 2023-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatstempname',
            options={'ordering': ['-step']},
        ),
        migrations.AddField(
            model_name='whatsmsg',
            name='lang',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
