# Generated by Django 4.0 on 2023-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_whatstempname_options_whatsmsg_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatstempmsg',
            name='btn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
