# Generated by Django 4.0 on 2023-11-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('whatsapp', '0003_whatstempmsg_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsmsg',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.businessunit'),
        ),
    ]
