# Generated by Django 4.0 on 2023-11-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsmsg_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatstempmsg',
            name='next',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
