# Generated by Django 4.0 on 2023-11-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatstempmsg_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsmsgreply',
            name='flt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
