# Generated by Django 4.0 on 2023-11-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsmsgreply_flt'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsmsg',
            name='flt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
