# Generated by Django 4.0 on 2023-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_whatsmsg_flt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsmsg',
            name='flt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsmsg',
            name='lang',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
