# Generated by Django 4.0 on 2023-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_alter_whatsmsg_flt_alter_whatsmsg_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatstempmsg',
            name='en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatstempmsg',
            name='lg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
