# Generated by Django 4.0 on 2023-11-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_appcategory_mcat_invcategory_mcat'),
        ('whatsapp', '0009_alter_whatstempmsg_en_alter_whatstempmsg_lg'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatstempname',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.businesscategory'),
        ),
    ]
