# Generated by Django 4.0 on 2023-11-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_whatstempname_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatstempmsg',
            old_name='lg',
            new_name='l_1',
        ),
        migrations.AddField(
            model_name='whatstempmsg',
            name='l_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatstempmsg',
            name='l_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatstempmsg',
            name='l_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatstempmsg',
            name='l_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
