# Generated by Django 4.0 on 2023-11-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_rename_lg_whatstempmsg_l_1_whatstempmsg_l_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsmsg',
            name='lang',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
