# Generated by Django 4.0 on 2023-11-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0012_alter_whatsmsg_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsmsgconve',
            name='reptxt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsmsgreply',
            name='reptxt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatsmsgreply',
            name='reply',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
