# Generated by Django 4.0 on 2023-11-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_invcategory_cat_lc_inventory_description_lc_and_more'),
        ('whatsapp', '0008_alter_whatsmsg_flt_alter_whatsmsg_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='No Note', null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, default='CREATED', max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.businessunit')),
                ('conver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsmsg')),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerprofile')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, default='CREATED', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.inventory')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
