# Generated by Django 4.0 on 2023-11-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_alter_whatstempmsg_en_alter_whatstempmsg_lg'),
        ('customers', '0011_slotbooking'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartServiceLst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_nm', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, default='CREATED', max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('appoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.appointment')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.businessunit')),
                ('conver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsmsg')),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerprofile')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.serviceholiday')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.slotbooking')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
