# Generated by Django 4.0 on 2023-11-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_alter_whatstempmsg_en_alter_whatstempmsg_lg'),
        ('customers', '0011_slotbooking'),
        ('cart', '0002_cartservicelst'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, default='CREATED', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.businessunit')),
                ('conver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsmsg')),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerprofile')),
            ],
        ),
    ]
