# Generated by Django 4.0 on 2023-11-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cliniccart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniccart',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
